version: '3'
services:
  web:
    build: .
    ports:
      - "3000:80"
    volumes:
      - .:/var/www/html
    environment:
      - DB_HOST="root"
      - DB_USER=$"root"
      - DB_PASSWORD="1234"
      - DB_NAME="cine"
    depends_on:
      - db
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: cine
    volumes:
      - ./sql:/docker-entrypoint-initdb.d